name = "Yao Yuqi"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Husband, Father, PHPer, Javaer, Full Stack Engineer."
company = "Luyi Master"
location = "Chengdu, China"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
